name: flutter_huoshu_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fish_redux: ^0.3.7
  flutter_localizations:
    sdk: flutter
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.4.1
  dio: ^3.0.9
  json_serializable: ^3.0.0
  focus_detector: ^1.0.3 #声明周期onresume方法
  shared_preferences: ^2.0.9
  permission_handler: ^3.0.0 #权限库
  video_player: 2.1.10 #视频播放
  orientation: ^1.2.0
  event_bus: ^1.1.1
  screen: ^0.0.5
  image_picker:
    path: plugins/image_picker
  oktoast: 3.1.5 #Toast
  url_launcher: ^5.1.2 #用来打开外部  电话/qq
  tobias: 1.1.0 #支付宝
  photo_view: 0.4.2
  flutter_slidable: ^0.6.0
  flutter_download_plugin:
    path: plugins/flutter_download_plugin
  flutter_plugin_user_agent_auth:
    path: plugins/flutter_plugin_user_agent_auth
  extended_nested_scroll_view: 0.3.6
  connectivity: ^0.4.4
  path_provider: ^2.0.7 #文件插件
  flutter_widget_from_html_core: 0.2.4+4 #富文本
  http_server: ^0.9.8+3 #测试导包

  #--start-- 把GitHub仓库的代码转移到码云
  flutter_custom_bottom_tab_bar:
    git:
      url: https://gitee.com/HuoShuWangLuo/flutter_custom_bottom_tab_bar.git
      ref: "1.0"
  flutter_webview_plugin:
    git:
      url: https://gitee.com/HuoShuWangLuo/flutter_webview_plugin.git
      ref: "0.3.114"
  sharesdk_plugin: ^1.3.4
#  fake_wechat:
#    git:
#      url: https://gitee.com/HuoShuWangLuo/fake_wechat.git
  flutter_downloader: #下载框架
    git:
      url: https://gitee.com/HuoShuWangLuo/flutter_downloader.git
      ref: "v1.4.4"
  #--end--

  flutter_html: 0.11.1
  stream_transform: ^1.1.0
  pull_to_refresh: 2.0.0 #聊天界面用到
  extended_text: 7.0.0
  extended_text_field: 8.0.0
  extended_text_library: 7.0.0
  wakelock: ^0.1.4+2 #防息屏库
  webview_flutter: ^2.3.1
  expandable: ^5.0.1
  flutter_image_compress: ^1.1.0

#  flutter_download_sign_plugin:
#    path: plugins/flutter_download_sign_plugin
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  build_runner: ^1.5.2

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
